[package]
name = "little-game"
version = "0.1.0"
authors = ["Mårten Åsberg <marten.asberg@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.20.0"
font-kit = "0.5.0"
minifb = "0.19.3"
rand = "0.8.3"
raqote = "0.7.14"
